# Generated by Django 3.2.7 on 2022-08-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20220830_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Makaleye Fotoğraf Ekleyin'),
        ),
    ]
